"""
Citizen Services Portal — Verification endpoint.

GET /verify?d=<doc_id>  — public; verify a signed document's FALCON-512 signature.

The QR code generated by /documents/{id}/qr embeds a URL of this shape.
Anyone with the QR can verify the document without authentication.
Every verification attempt is logged to audit_log for non-repudiation.
"""
import uuid as uuid_lib
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.crypto.falcon_service import get_public_key, verify_signature
from app.database import get_session
from app.models import AuditLog, Document, DocumentStatus, User

router = APIRouter(tags=["verify"])


async def _log_verify_attempt(
    session: AsyncSession,
    request: Request,
    doc_id: uuid_lib.UUID,
    outcome: str,
    extra: dict[str, Any] | None = None,
) -> None:
    """Insert an audit_log row for a /verify request. Best-effort, swallows errors."""
    try:
        log = AuditLog(
            actor_id=None,  # public endpoint, no authenticated actor
            action="verify_qr",
            target_type="document",
            target_id=doc_id,
            extra_metadata={"outcome": outcome, **(extra or {})},
            ip_address=(request.client.host if request.client else None),
            user_agent=request.headers.get("user-agent"),
        )
        session.add(log)
        await session.commit()
    except Exception:
        # Don't let logging failure break the verify response
        await session.rollback()


@router.get("/verify")
async def verify_document(
    request: Request,
    d: uuid_lib.UUID = Query(..., description="Document UUID from the QR code"),
    session: AsyncSession = Depends(get_session),
):
    """
    Verify a signed document.

    Response shape:
        {
            "valid":         bool,
            "doc_id":        uuid,
            "filename":      str,
            "file_hash":     sha256 hex,
            "file_size":     int (bytes),
            "status":        "signed" | "pending",
            "signed_at":     ISO timestamp | null,
            "signer_email":  email | null,
            "public_key_ref": short hash | null,
            "reason":        only present if valid=false
        }
    """
    # Look up the document
    result = await session.execute(select(Document).where(Document.id == d))
    doc = result.scalar_one_or_none()

    if doc is None:
        await _log_verify_attempt(session, request, d, "not_found")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found",
        )

    # Build base response from DB columns
    response: dict[str, Any] = {
        "doc_id": str(doc.id),
        "filename": doc.filename,
        "file_hash": doc.file_hash,
        "file_size": doc.file_size,
        "status": doc.status.value,
        "signed_at": doc.signed_at.isoformat() if doc.signed_at else None,
        "public_key_ref": doc.public_key_ref,
    }

    # Pull signer email
    if doc.signed_by:
        sres = await session.execute(select(User).where(User.id == doc.signed_by))
        signer = sres.scalar_one_or_none()
        response["signer_email"] = signer.email if signer else None
    else:
        response["signer_email"] = None

    # Cannot verify a doc that was never signed
    if doc.status != DocumentStatus.SIGNED or doc.falcon_signature is None:
        response["valid"] = False
        response["reason"] = f"Document not signed (status={doc.status.value})"
        await _log_verify_attempt(session, request, d, "not_signed")
        return response

    # Re-read the PDF and verify the signature
    file_path = Path(doc.storage_path)
    if not file_path.exists():
        response["valid"] = False
        response["reason"] = "File missing on server"
        await _log_verify_attempt(session, request, d, "file_missing")
        return response

    pdf_bytes = file_path.read_bytes()
    public_key = get_public_key()
    is_valid = verify_signature(pdf_bytes, doc.falcon_signature, public_key)

    response["valid"] = is_valid
    if not is_valid:
        response["reason"] = (
            "Signature verification failed — document may have been tampered with"
        )

    await _log_verify_attempt(
        session, request, d, "valid" if is_valid else "invalid"
    )
    return response
