"""
Citizen Services Portal — Verification endpoint.

GET /verify?d=<doc_id>  — public; verify a signed document's ML-DSA-44 signature.

The QR code generated by /documents/{id}/qr embeds a URL of this shape.
Anyone with the QR can verify the document without authentication.
Every verification attempt is logged to audit_log for non-repudiation.
"""
import uuid as uuid_lib
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.audit_utils import record_audit
from app.crypto.mldsa_service import verify_document as mldsa_verify_document
from app.database import get_session
from app.models import Document, DocumentStatus, User

router = APIRouter(tags=["verify"])


def is_qr_expired(expires_at: datetime, now: datetime | None = None) -> bool:
    """Return True when online QR verification metadata has expired."""

    if expires_at.tzinfo is None:
        expires_at = expires_at.replace(tzinfo=timezone.utc)
    current_time = now or datetime.now(timezone.utc)
    return current_time >= expires_at


async def _log_verify_attempt(
    session: AsyncSession,
    request: Request,
    doc_id: uuid_lib.UUID,
    outcome: str,
    extra: dict[str, Any] | None = None,
) -> None:
    await record_audit(
        session,
        action="verify_qr",
        outcome=outcome,
        request=request,
        target_type="document",
        target_id=doc_id,
        extra=extra,
    )


@router.get("/verify")
async def verify_document(
    request: Request,
    d: uuid_lib.UUID = Query(..., description="Document UUID from the QR code"),
    session: AsyncSession = Depends(get_session),
):
    """
    Verify a signed document.

    Response shape:
        {
            "valid":         bool,
            "doc_id":        uuid,
            "filename":      str,
            "file_hash":     sha256 hex,
            "file_size":     int (bytes),
            "status":        "signed" | "pending",
            "signed_at":     ISO timestamp | null,
            "signer_email":  email | null,
            "public_key_ref": short hash | null,
            "reason":        only present if valid=false
        }
    """
    # Look up the document
    result = await session.execute(select(Document).where(Document.id == d))
    doc = result.scalar_one_or_none()

    if doc is None:
        await _log_verify_attempt(session, request, d, "not_found")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found",
        )

    # Build base response from DB columns
    response: dict[str, Any] = {
        "doc_id": str(doc.id),
        "filename": doc.filename,
        "file_hash": doc.file_hash,
        "file_size": doc.file_size,
        "status": doc.status.value,
        "signed_at": doc.signed_at.isoformat() if doc.signed_at else None,
        "public_key_ref": doc.public_key_ref,
    }

    # Pull signer email
    if doc.signed_by:
        sres = await session.execute(select(User).where(User.id == doc.signed_by))
        signer = sres.scalar_one_or_none()
        response["signer_email"] = signer.email if signer else None
    else:
        response["signer_email"] = None

    # Cannot verify a doc that was never signed
    if doc.status != DocumentStatus.SIGNED or doc.falcon_signature is None:
        response["valid"] = False
        response["reason"] = f"Document not signed (status={doc.status.value})"
        await _log_verify_attempt(session, request, d, "not_signed")
        return response

    if doc.signing_public_key is None:
        response["valid"] = False
        response["reason"] = "Signing public key missing for this document"
        await _log_verify_attempt(session, request, d, "public_key_missing")
        return response

    if doc.qr_expires_at is None:
        response["valid"] = False
        response["reason"] = "QR verification metadata has not been issued"
        await _log_verify_attempt(session, request, d, "qr_not_issued")
        return response

    if is_qr_expired(doc.qr_expires_at):
        response["valid"] = False
        response["reason"] = "QR verification metadata expired"
        await _log_verify_attempt(session, request, d, "expired")
        return response

    # Re-read the PDF and verify the signature with its signing-time key.
    file_path = Path(doc.storage_path)
    if not file_path.exists():
        response["valid"] = False
        response["reason"] = "File missing on server"
        await _log_verify_attempt(session, request, d, "file_missing")
        return response

    pdf_bytes = file_path.read_bytes()
    is_valid = mldsa_verify_document(
        pdf_bytes,
        doc.falcon_signature,
        doc.signing_public_key,
        expected_hash_hex=doc.file_hash,
    )

    response["valid"] = is_valid
    if not is_valid:
        response["reason"] = (
            "Signature verification failed — document may have been tampered with"
        )

    await _log_verify_attempt(
        session, request, d, "valid" if is_valid else "invalid"
    )
    return response
